/**
 * GET /api/reference | the corrections, the rulings and everything verbatim.
 */

import {
  getAddedTopics,
  getBreaks,
  getClockFacts,
  getCorrections,
  getCosts,
  getCourseRulings,
  getCourseTopicMap,
  getDeadLinks,
  getDoNotBuy,
  getFalsifier,
  getFocusRules,
  getHonestyRules,
  getHonestyTests,
  getLaunchDays,
  getMachineInventory,
  getNightSegments,
  getOwnedCourses,
  getSkipList,
  getStackVersions,
  getSubjects,
  getTrackers,
  getTrackingFiles,
  getVerificationLog,
  getVideoRules,
} from '@/lib/db/reference';
import { authedRoute, jsonOk } from '@/lib/server/route';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export const GET = authedRoute(async () => {
  const [
    corrections,
    stack,
    breaks,
    skip,
    doNotBuy,
    added,
    costs,
    dead,
    trackers,
    trackingFiles,
    clock,
    subjects,
    launch,
    night,
    machine,
    focus,
    honestyTests,
    honestyRules,
    courses,
    rulings,
    topicMap,
    videoRules,
    falsifier,
    log,
  ] = await Promise.all([
    getCorrections(),
    getStackVersions(),
    getBreaks(),
    getSkipList(),
    getDoNotBuy(),
    getAddedTopics(),
    getCosts(),
    getDeadLinks(),
    getTrackers(),
    getTrackingFiles(),
    getClockFacts(),
    getSubjects(),
    getLaunchDays(),
    getNightSegments(),
    getMachineInventory(),
    getFocusRules(),
    getHonestyTests(),
    getHonestyRules(),
    getOwnedCourses(),
    getCourseRulings(),
    getCourseTopicMap(),
    getVideoRules(),
    getFalsifier(),
    getVerificationLog(),
  ]);

  return jsonOk({
    corrections,
    stack_versions: stack,
    breaks,
    skip_list: skip,
    do_not_buy: doNotBuy,
    added_topics: added,
    costs,
    dead_links: dead,
    trackers,
    tracking_files: trackingFiles,
    clock_facts: clock,
    subjects,
    launch_days: launch,
    night_segments: night,
    machine_inventory: machine,
    focus_rules: focus,
    honesty_tests: honestyTests,
    honesty_rules: honestyRules,
    owned_courses: courses,
    course_rulings: rulings,
    course_topic_map: topicMap,
    video_rules: videoRules,
    falsifier,
    verification_log: log,
  });
});
